### ISSUE TITLE
Explicitly state JavaScript modules used in configuration

### ISSUE THREAD

**Issue by bryanjos** [elixirscript/elixirscript#225]
This is a proposal to state in configuration what third-party ES modules will be in elixirscript code. Something like

```elixir
     elixir_script: [ 
        input: "lib/exjs", 
        output: "priv/js",
        format: :es,
        js_modules: [
          {React, "react"},
          {Underscore, "underscore", default: false}
       ]
     ]
```

This would replace `JS.import` as it stands today.

The stated modules would be added to each compiled module's list of imports

**Comment by knewter** [comment]
this looks very cool :)
