### ISSUE TITLE
Enum.member? not translated correctly

### ISSUE THREAD

**Issue by mrdziuban** [elixirscript/elixirscript#248]
On master `Elixir.Enum.member__qmark__` is not translated properly to `Bootstrap.Enum.member__qmark__`, but other `Enum` functions are. I tried looking around in the code but wasn't able to find where the translation for that particular function was happening.

**Comment by bryanjos** [comment]
I can give it a check a bit later. That's weird that's the only one doing it. The code that should handle it is here: https://github.com/elixirscript/elixirscript/blob/master/lib/elixir_script/translator.ex#L275

I think that's the only place off the top of my head. Enum is the only module still in javascript until #186 is completed.

**Comment by bryanjos** [comment]
@mrdziuban I wasn't able to reproduce the error. I made a test just to make sure and it passes:
https://github.com/elixirscript/elixirscript/commit/cf726c22b64a7a1a179b71ccf165eb067d4e7dc8

**Comment by mrdziuban** [comment]
@bryanjos Sorry, I think I was mistaken on what actually causes the issue. It looks like it **might** happen when translating `case...in` statements, but I'm still not fully sure. If you run this:

```bash
elixirscript -c ':console.log("test")' --elixir
```

and inspect the output, you'll see several occurrences of `Elixir.Enum.member__qmark__` in stdlib functions. Here's [a gist](https://gist.github.com/mrdziuban/55293da639a9f67d91a9f8d09d4e607b) I made with the output of that command.

**Comment by bryanjos** [comment]
I thought it could possibly be with the `in` translation, but that seems to be correct as well. I did update the test I created to make sure that `Elixir.Enum.member__qmark__` is not in the generated output just in case

**Comment by mrdziuban** [comment]
If you run the command above, you don't see any occurrences of `Elixir.Enum.member__qmark__` like in my gist? I can't get it to fail in the tests, but I can consistently get it to happen on the command line. This is what I'm doing:

```bash
MIX_ENV=prod mix do clean, compile, dist
tar xvzf dist/elixirscript.tar.gz -C dist
./dist/dist/elixirscript/bin/elixirscript '
defmodule TestMod do
  def test_func(x) do
    ints = [1,2,3]
    case x in ints do
      true -> "in"
      false -> "out"
    end
  end
end' --elixir
```

And the last chunk of the output (where `TestMod` is defined) is:

```js
Bootstrap.Core.Functions.build_namespace(Elixir, 'Elixir.TestMod').__load = function(Elixir) {
    if (Bootstrap.Core.Functions.build_namespace(Elixir, 'Elixir.TestMod').__exports)
        return Bootstrap.Core.Functions.build_namespace(Elixir, 'Elixir.TestMod').__exports;

    const test_func = Bootstrap.Core.Patterns.defmatch(Bootstrap.Core.Patterns.clause([Bootstrap.Core.Patterns.variable()], function(x) {
        let [ints] = Bootstrap.Core.Patterns.match(Bootstrap.Core.Patterns.variable(), Object.freeze([1, 2, 3]));

        return Bootstrap.Core.Patterns.defmatch(Bootstrap.Core.Patterns.clause([true], function() {
            return 'in';
        }), Bootstrap.Core.Patterns.clause([false], function() {
            return 'out';
        })).call(this, Elixir.Enum.member__qmark__(ints, x));
    }));

    const __exports = {
        test_func
    };

    Bootstrap.Core.Functions.build_namespace(Elixir, 'Elixir.TestMod').__exports = __exports

    const Elixir$ElixirScript$Kernel = Bootstrap.Core.Functions.build_namespace(Elixir, 'Elixir.ElixirScript.Kernel').__load(Elixir);

    return __exports;
}
```

It has `Elixir.Enum.member__qmark__(ints, x)`. Note that storing `ints` in a variable is necessary to reproduce.

**Comment by bryanjos** [comment]
I think I see what's happening. I made a new issue for it #249. Basically the code going through those functions don't pass through the Elixir compiler and so the modules are never loaded to ensure it's expanding macros from the ElixirScript standard library instead of the Elixir one. 

One day hopefully they are one in the same
