### ISSUE TITLE
Implement Tail Call Recursion

### ISSUE THREAD

**Issue by bryanjos** [elixirscript/elixirscript#270]
Connects to #221 

Elixirscript does not support tail call recursion. The connected issue shows the steps that have been taken to try to get it working.

This issue is to either

- [ ]  Implement Tail Call Recursion in Elixirscript directly 

OR

- [ ] Implement Tail Call Recursion [here](https://github.com/elixirscript/tailored), the library used to make pattern matching functions

There are some articles, posts, and projects found to implement Tail Call Recursion and Optimization in JavaScript using trampolining. I've tried a couple of techniques, but haven't found anything that works that doesn't require rewriting how functions are written. I also am not sure if the way that pattern matched functions are created have any negative effects.

This can be considered done when the example in #221 doesn't throw a stack error

**Comment by Qqwy** [comment]
I believe that implementing it in Tailored would be better; the example code in the README already shows a recursive definition of the Factorial function which you'd like to be tail-recursive.

> but haven't found anything that works that doesn't require rewriting how functions are written.
I am fairly certain that this indeed is the case. I expect that there is a mistake in https://github.com/elixirscript/tailored/blob/master/src/tailored/defmatch.js#L38 and that when we fix it, it will work. I'll investigate in more detail once I have the time the next few days.

**Comment by troglotit** [comment]
I dug a little bit, and, as far as I can understand, to trampolines to work (or any stack allocation elimination), functions should be called in tail call position. And to implement refactoring to tail call position is a kinda hard problem with grunt solution, especially for mutually recursive stuff.

I googled a bit, and found https://github.com/elixir-lang/elixir/issues/6251 which means Elixir itself does have that kind of stuff. I tried to search for tail call elimination phase in Elixir source code and didn't succeed. But I believe going for that transformation is a way to go with TCO.

That is my observation, and I don't have Elixir or BeamVM experience at all to know if it's possible to translate that kind of stuff for Javascript.

**Comment by bryanjos** [comment]
Maybe the new format of how functions are compiled will help here. Instead of calling a function to produce a function the does pattern matching, now an actual named function is created with if statements for each function pattern. There is a part of me that believes because the old way dealt with a bunch of anonymous functions so it was possible that may have effected the stack.

**Comment by bryanjos** [comment]
Was able to implement this thanks in part to the new function translation
