### ISSUE TITLE
Compile functions as async functions

### ISSUE THREAD

**Issue by bryanjos** [elixirscript/elixirscript#280]
ES2017 introduces async functions. It may be useful for elixirscript to produce async functions instead of normal functions. Is this something worth while? That is the question. It may or may not unlock the ability to implement `receive` at some point, but more research would be needed to know.

**Comment by bryanjos** [comment]
After experimenting a bit, this would be a bigger task than originally thought, but still may be a way to go

**Comment by bryanjos** [comment]
Reviving

**Comment by bryanjos** [comment]
Opening again. I've started working on this again in the `async_switch` branch

**Comment by bryanjos** [comment]
The async compilation branch seems to be at parity with master. Only problem I've seen so far is that with the Todo example app, there are issues with react's event pooling.

**Comment by bryanjos** [comment]
The good news is that compiling to async functions did work, but using async/await with a scheduler to achieve processes has not. I'm thinking about compiling to generator functions instead. Those are at least known to work as processes. My concern there is what to do when a javascript function expects a callback. I'm guessing some function that wraps around the generator will be needed in those cases

**Comment by vans163** [comment]
I think re implementing an actor model should be out of scope for elixirscript, maybe elixirscript_actor, it just seems in the same path as elixirscript_vdom,  the question is do you want a vdom and actor model baked in? it seems not good for maintainability and code separation to me.

Having everything an async function thought is different.  It would allow the code to function like its written (death to promises), perhaps with an extra await() on the elixir side.  If everything is an async function its a huge win, we can now write 
```
r = async(API.Query())
r = async(r.stream())

VS

API.Query().then(fn(r)->
    r.stream()
end).then(fn(r)->
    r
end)
```

If async functions are working without schedulers it would be amazing.

**Comment by bryanjos** [comment]
I admit using it with the branch was nice, but the end goal is to support `receive`. Supporting `receive` is within the scope of ElixirScript and need a way to do that. If there is a way to do it with standard async/await than that would be optimal.

I am thinking about compiling to generators instead. Processes and receive all work in that case. The only thing would be to create a function that takes a generator function and return a function for using as callbacks with JavaScript things that require callbacks.

These are all long term plans. This probably won't make the next version and any changes should not effect the FFI at all.

**Comment by vans163** [comment]
I guess we have differing views on receive. I am thinking in terms of multiple backends to run the processes: generators, web workers, wasm future constructs for multithreading, etc.  Personally I would like to be able to plug and swap the "engine" vs being forced to have it all in 1 project.

Receive is more an engine construct related to the actor model vs a feature of the syntactical language.  Seemingly simple process mailboxes is a damn complex thing to do, especially if you are multiplexing it all on 1 thread.  It just seems to me the actor model implementation of elixirscript (receive) will be subject to a lot of tuning and performance tweaks, plus it looks like a project that would be useful in javascript land as a standalone.

**Comment by bryanjos** [comment]
Closing this one. I don't think it's going anywhere
