### ISSUE TITLE
Add all Standard Library Error modules

### ISSUE THREAD

**Issue by bryanjos** [elixirscript/elixirscript#284]
In particular, all the ones list in the `Exceptions` portion of the [Elixir docs](https://hexdocs.pm/elixir). Some are implemented [here](https://github.com/elixirscript/elixirscript/blob/master/priv/std_lib/exceptions.ex)

**Comment by theocodes** [comment]
hey @bryanjos 

I'm happy to take a stab at this, if you like? I've been meaning to get involved with the project for a while and this might be simple enough to help me warm up to the code base.. 

Cheers

**Comment by bryanjos** [comment]
@theocodes cool! Most of the Elixir exceptions are defined [here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/exception.ex#L490). Right now ElixirScript can't accurately support the ones with message and exception functions (see #288) but the simple ones should be ok.

**Comment by theocodes** [comment]
@bryanjos I've gone though all of the exceptions defined in elixir and from what I can tell the only 2 that won't require #288 implemented first, are `ArithmeticError` and `Enum.EmptyError`. The rest seem to make heavy use of error context that is either passed to `defexception` or the `message` function itself which at the moment is implemented as an attribute in the struct, as you know.

I'm happy to open a PR for the 2 exceptions in question but at this point I can't help but to think we would be better of tackling #288 first and then implementing all of the exceptions on top of that?

Let me know your thoughts
Thanks

**Comment by bryanjos** [comment]
Yeah probably best that #288 is handled first. That one is a little complicated by the overridable functions, but there may be a way of preprocessing those like the other overridable functions.
