### ISSUE TITLE
How do I import modules? (JS.import not working for me)

### ISSUE THREAD

**Issue by MainShayne233** [elixirscript/elixirscript#298]
Freaking love this project; I appreciate your ambition :).

I'm playing with the frontend boilerplate, and I've been trying:
```elixir
JS.import React, "react"
```

But get
```
** (UndefinedFunctionError) function JS.import/2 is undefined or private
```

I imagine I am missing a step, but can't quite figure it out.

**Comment by bryanjos** [comment]
To use a javascript module, you have to configure them ahead of time. There are some instructions [here](https://github.com/elixirscript/elixirscript/blob/master/JavascriptInterop.md#javascript-modules)

**Comment by MainShayne233** [comment]
Sweet! Totally missed that. Thanks for the quick response :)
