### ISSUE TITLE
module caching

### ISSUE THREAD

**Issue by bryanjos** [elixirscript/elixirscript#310]
Caching of modules that have been compiled. The cached version should be used if the beam file has not been modified since the module was compiled. When the beam file is modified, that cache should be invalidated.

**Comment by bryanjos** [comment]
I think steps to make this happen include:

* Keeping track of the beam file's modified date
* Storing the generated JavaScript AST for modules
* When a beam file's modified date does not match, do a full compile

What I'm not sure of is how to handle cases when the module itself hasn't changed and some other module uses a function on that module that was previously unused and not compiled. I am am guessing in order to handle that, the cache may need to keep track of functions compiled. Then at least if one if the above happens, it can force a cache invalidation

**Comment by bryanjos** [comment]
I am also not sure currently how the cache should be stored

**Comment by vans163** [comment]
cache storage location could be set with a mix param? right beside input, output, etc?
a default location in the priv directory seems right, perhaps under elixir_script/ folder which is already required.

**Comment by bryanjos** [comment]
There isn't a need for the caching to be configurable or in the priv folder. The best places are probably the `_build` folder somewhere or a temp directory

**Comment by vans163** [comment]
temp directories outside _build folder will be annoying to deal with in this case.  I thought you might want to use the same cache with multiple elixirscript projects.

if by default temp dir is outside _build, such as in ~/.config or something, it gets really annoying to pass through the project as a volume to containers and such.

**Comment by vans163** [comment]
```
19:20:32.543 [info]  FindUsedModules took: 2263
19:20:32.894 [info]  FindUsedFunctions took: 351
19:20:33.638 [info]  Translate took: 744
19:20:34.236 [info]  Output took: 598
19:20:34.249 [info]  Compile took: 3970
```

Some current compilation times.

**Comment by bryanjos** [comment]
It could be related to how the state is stored. It's possible that step will be slowest because it does the loading of modules for most of modules being compiled

**Comment by bryanjos** [comment]
Closing this in favor of #438 which is a bit more directed
