### ISSUE TITLE
Qt

### ISSUE THREAD

**Issue by ShalokShalom** [elixirscript/elixirscript#340]
Hi there :D 

I love Qt and like to code in it.

And I like to choose Elixir as programming language, since it offers this nice, Ruby like syntax combined with functional programming and all these awesome features like Pattern matching and the super Pipe Operator. 

Elixirscript is the perfect connection between both projects. 

Quick 2 is one of Qt's librarys and offers a JSON like programming language called QML, which is capable to draw multi platform, hardware accelerated, native looking, animated, automatic scaling and desktop/mobile friendly interfaces in a very easy manner. 

Elixirscript already support that, since QML can simply import .js files for the logic. ^-^

Javascript and QML are the main languages in Qt in addition to C++, that means including full support, semantic syntax highlighting and high optimisation.

It is even possible to transcompile JS/QML code into C++, with the so called Qt Quick Compiler.

KDE decides to ship the QML files anyway, since the performance difference for little widgets and apps in real world scenarios is very tiny, while these files offer us the option to adjust very detailed changes in a dynamic way. 

In addition to that is it possible to use it also for web interfaces, since there is a JavaScript library that converts QML into web languages, even two of them to be precise. :)

Since QML is implemented as a kind of extension to JavaScript, is it possible to use JS inline at .qml documents for the logic. 

So is it possible to describe the interface and the logic in the same file, also to combine both with things like width * 2 and so on.

I like to see your opinion about a broader integration :D

So, support for all the other Qt and maybe even the KDE libs. 
If there are any challenges into which I can contribute, let me know. :)

I am willing to help, also with documentation and so on, while I am still a newbie. :)

Thanks a lot in advance ^-^

**Comment by bryanjos** [comment]
Hi @ShalokShalom 

While I'm not in favor of adding any Qt elements to ElixirScript itself, I am interested to see how what is written here can be used with Qt. If it supports JavaScript and the output from ElixirScript works with Qt and QML files that would be cool.
