### ISSUE TITLE
Rename `foreign` to `defexternal`

### ISSUE THREAD

**Issue by OvermindDL1** [elixirscript/elixirscript#341]
Things starting with `def` tend to be formatted by the auto-formatter better as well as color coded better.  Could leave the existing `foreign` call but also add a delegate of `defforeign` or perhaps `defexternal` or so (`external` is OCaml's keyword for FFI)?

**Comment by bryanjos** [comment]
@OvermindDL1 I think you sold me on `defexternal`. Because having `def` is better for the reasons you said and `defforeign` I could see causing issues with the double `f`.
