### ISSUE TITLE
Make sure true, false, and nil are treated as atoms

### ISSUE THREAD

**Issue by bryanjos** [elixirscript/elixirscript#349]
`true` and `false` are translated into booleans in JavaScript
`nil` is translated to `null`

Each of these in Elixir are treated as atoms and should be done so in ElixirScript.

The only changes here I believe are to update the atom functions in the Erlang compatibility layer to look for the above as special cases

**Comment by vans163** [comment]
I am trying to think of cases where you want the true/false to be a javascript true/false, perhaps something like:

if javascriptObject.property == true do
end

(still no idea how to access js properties though)
