### ISSUE TITLE
Using some String functions adds 16.9MB to output

### ISSUE THREAD

**Issue by jclem** [elixirscript/elixirscript#353]
I am trying to compile the [`OT.Text`](https://github.com/jclem/ot_ex/blob/master/lib/ot/text.ex) module from https://github.com/jclem/ot_ex and am finding that even if I try to compile only the rather small [`OT.Text.Component`](https://github.com/jclem/ot_ex/blob/master/lib/ot/text/component.ex) module, the presence of `String.slice/3` adds 16.9MB to the JavaScript output.

I have also found that the presence of `String.split_at/2` adds the same amount. Simply commenting out the lines that include either `String.slice/3` or `String.split_at/2` reduces my output from 18MB to 1.1MB.

In order to check that I wasn't doing something wrong, I attempted to compile just this module:

```elixir
defmodule Test do
  def split_abc do
    String.split_at("ABC", 2)
  end
end
```

Its output is also 18MB. What's causing this very large compilation size, and can it be fixed? This is with ElixirScript v0.30.0

*btw I forgot to say, thanks for spending your time on ElixirScript, I'm super super super excited about it*

**Comment by bryanjos** [comment]
Some of the string functions add in the unicode database. ElixirScript tries to get around this by replacing some calls in string with its own version.

https://github.com/elixirscript/elixirscript/blob/master/lib/elixir_script/lib/string.ex

Adding in an implementation of `split_at` there should resolve the issue for that function.

**Comment by jclem** [comment]
Excellent, thanks for the direction! I'll see if I can spend some time on this this week.

**Comment by jclem** [comment]
@bryanjos One issue with implementing `split_at` is that it'd almost certainly involve either a) accepting that JavaScript isn't very unicode-aware, and that splits will work differently than they do in Elixir or b) using a library (maybe lodash) that is unicode-aware to properly split strings containing Emoji into arrays. 

What are your thoughts on this?

**Comment by bryanjos** [comment]
@jclem I guess I thought javascript was smart enough to handle it naturally. I think it's still possible to make it work though. 

This might take some implementing in JavaScript but it looks like the String iterator is unicode aware

```js
const testString = "😀abélkm"
for(const b of testString) {
  console.log(b)
}
```

A javascript function that takes a string and an index and splits on that could work. It could turn the string into an array of unicode characters which could then be split and then join the characters back into the appropriate strings.

There a javascript functions that ElixirScript uses that are defined here:
https://github.com/elixirscript/elixirscript/blob/master/src/javascript/lib/core/functions.js

I can start implementing something to make it work

**Comment by bryanjos** [comment]
I was able to implement it correctly

**Comment by jclem** [comment]
@bryanjos Unfortunately, `for..of` doesn't account for the zero-width joiner (`\u200d`) that's used in many emoji:

```javascript
const testString = '👨‍👨‍👧‍👦';
for (const char of testString) {
  console.log(testString);
}

// 👨
// \u200d
// 👩
// \u200d
// 👦
// \u200d
// 👦
```

There's a good article on this horrendous conundrum [here](https://mathiasbynens.be/notes/javascript-unicode) and an example working grapheme splitter [here](https://github.com/orling/grapheme-splitter).

**Comment by bryanjos** [comment]
@jclem It does look like a bigger problem indeed. May try including that library here directly since the license is compatible.

**Comment by vans163** [comment]
Seems this is more a javascript issue then elixirscript.  I dont think elixirscript is meant to fix javascript problems.

**Comment by bryanjos** [comment]
I added the grapheme-splitter as a dependency. Hopefully that resolves the issues for now
