### ISSUE TITLE
function arity on JS side started giving bad match spec since version 0.30.0

### ISSUE THREAD

**Issue by vans163** [elixirscript/elixirscript#357]
```
onBlur: fn-> :'window.console'.log "blurred!" end

Uncaught MatchError: No match for: [object Object],[object Event]
```

Before 0.30.0 this was fine and valid.

**Comment by bryanjos** [comment]
This is intentional. Even though JavaScript drops parameters not used that are given to a function, ElixirScript matches on all parameters given.
