### ISSUE TITLE
throw/1 is not implemented. raise/1 does not work

### ISSUE THREAD

**Issue by vans163** [elixirscript/elixirscript#359]
```
Uncaught TypeError: ElixirScript.Core.erlang.__throw__ is not a function
```
```
raise(:atom)

Uncaught ReferenceError: atom is not defined
```

Perhaps it should be added to here https://github.com/elixirscript/elixirscript/issues/306?

**Comment by bryanjos** [comment]
I made a PR to fix throw compilation. For the `raise` example, it expects either a string or a module/atom which it calls `exception` on. So the above would not work. https://hexdocs.pm/elixir/Kernel.html#raise/1

**Comment by vans163** [comment]
bad example
```
raise("atomm")

Uncaught Tuple {values: Array(2), length: 2}
```

Its not very informative, perhaps can be improved to look like an actual raise occured?

**Comment by bryanjos** [comment]
Errors should definitely be improved. Raise eventually calls `:erlang.error` passing to it the result of `Exception.exception/1`. The implementation of `erlang.error` can be improved to show errors that look closer to what is expected

**Comment by bryanjos** [comment]
Reopening so discussion is seen

**Comment by bryanjos** [comment]
Error messages from raise or :erlang.error should now look like ones from Elixir
