### ISSUE TITLE
yarn should rebuild / check on a compile

### ISSUE THREAD

**Issue by vans163** [elixirscript/elixirscript#363]
If you change functions that affect ElixirScript.Core.Js, mix compile wont pick up on it. You need to force a recompile. 

This is maybe wrong and I dont know mix, but going to leave it out there.

**Comment by bryanjos** [comment]
I agree there should be a better way. I'm afraid to do it with `mix compile` because of what might happen when others use ElixirScript as a dependency. Maybe we should use a makefile instead?

**Comment by vans163** [comment]
I know rebar3 has pre/post hooks. Maybe mix has equivalent, in the hook you can determine if it makes sense to recompile Core.Js, for example by checksumming the js files, and comparing it to the checksum you embed in the head of ElixiScript.Core.Js or similar.

**Comment by bryanjos** [comment]
Took a look at the documentation and didn't see anything.

**Comment by vans163** [comment]
Does mix compile call into the elixir_script compiler if executed from another project, if no source files changed? If not, indeed its a strange problem to have.  Looking at google I came to the conclusion post compile hooks are just not community approved.

**Comment by bryanjos** [comment]
This is only a problem during development. I'm fine with using a makefile until something better comes along.
