### ISSUE TITLE
should ElixirScript.Core.js be prebuilt by default?

### ISSUE THREAD

**Issue by vans163** [elixirscript/elixirscript#364]
Its currently included under source control

**Comment by bryanjos** [comment]
I had it there for the benefit of using elixirscript from git in a mix project. It can probably be removed from source control now.

**Comment by vans163** [comment]
Seems https://github.com/elixirscript/elixirscript/issues/363 should be resolved first. It would be annoying to include elixir_script then wonder why it does not work, only to realize the tooling cant build it properly due to inability to execute yarn build.

**Comment by bryanjos** [comment]
Removed `ElixirScript.Core.js` from source control. It will still be inside of versions published to hex
