### ISSUE TITLE
Concurrent Compilation

### ISSUE THREAD

**Issue by bryanjos** [elixirscript/elixirscript#376]
Currently every module in each of the passes is done one by one. This task is to explore the possibility of spawning processes for walking and compilation of modules.

- [x] `find_used_modules`: Spawn walking of a module in a process
- [x] `find_used_functions`: Spawn walking of a module in a process
- [x] `translate`: Translate each module and function ast in a process

**Comment by OvermindDL1** [comment]
The way elixir does it is (as I recall) to start a genserver process per file to compile, as they compile if it hits something it needs to know another module about, like a `require` or `import` then it checks an ETS table to see if the information is there, if not it waits while setting an indicator until it is.  Once a file is compiled it loads its data into ETS for other things to test for.

**Comment by bryanjos** [comment]
That's true, but the good thing here is that ElixirScript doesn't have to wait for one to finish. It just needs to mark it in the state to let the processes know it has been found. Right now using an Agent, but could be an ETS table. I did a test yesterday using a `Task.async_stream/3`. I didn't notice any differences in speed.
