### ISSUE TITLE
object_to_map/1,2? 

### ISSUE THREAD

**Issue by vans163** [elixirscript/elixirscript#381]
We have a map_to_object, I realize there is probably a need to go object_to_map as well, with the same parameters. Same reversed parameters meaning the /2 version would have keys become symbols, perhaps existing_symbol option.

Do we need it, if so I can put in a pull.

**Comment by bryanjos** [comment]
It's probably a good idea to have those

**Comment by vans163** [comment]
Gotcha. This is a blocker https://github.com/elixirscript/elixirscript/issues/383

**Comment by vans163** [comment]
Knocked this one out here https://github.com/elixirscript/elixirscript/pull/387.

**Comment by bryanjos** [comment]
closed with #387
