### ISSUE TITLE
immutablility ==

### ISSUE THREAD

**Issue by vans163** [elixirscript/elixirscript#382]
These should be equal:
```
map1 = %{test: "map"}
map2 = %{test: "map"}
false = map1 == map2
```

**Comment by bryanjos** [comment]
Inlining the JavaScript's `==`, but think ElixirScript is going to have to define it's own equals methods at least for map and probably tuple, list, and bitstring

**Comment by vans163** [comment]
Would this break matches on the elixirscript side?
```
def func(map1, map2) when map1 ==map2, do: :matched
```

**Comment by bryanjos** [comment]
Yes it would not work there either. It would not effect pattern matching but would effect guards

**Comment by bryanjos** [comment]
The task here would be to:

- [ ] create an `equals` function in `erlang.js` that takes two parameters and export it
- [ ] inside of `equals` add code to compare 
  - [ ] maps
  - [ ] tuples
  - [ ] bitstrings
  - [ ] maps
  - [ ] pids
  - [ ] references
  - [ ] for everything else, fallback to javascript `==`
- [ ] Update compiler to translate `==` to the new `erlang.equals` function
