### ISSUE TITLE
map get peculiarity if map originates from JS side

### ISSUE THREAD

**Issue by vans163** [elixirscript/elixirscript#383]
```elixir
#Good
map = %{test: "my_value"}
map.test


function make_map() {
    let map = new Map();
    map.set(Symbol("test"), "my_value")
    return map;
}
window.make_map = make_map;

#Bad
map = :window.make_map()
null = Map.get(map, :test)

#Bad
map = :window.make_map()
null = map[:test]

#Bad
map = :window.make_map()
map.test

Uncaught Error: Property test not found in [object Map]
```

Perhaps related https://github.com/elixirscript/elixirscript/issues/380

The smoothest way to interop after parsing a json seems to be to turn the json into a map, hence how I bumped into this.

**Comment by vans163** [comment]
Using Symbol.for("test") makes it work, not sure why.

**Comment by OvermindDL1** [comment]
`Symbol("blah")` makes a new symbol of name "blah".  `Symbol.for("blah")` looks up a symbol named `"blah"` and returns it if it exists else it makes a new one and returns it.
