### ISSUE TITLE
Symbols are not a good replacement for atoms?

### ISSUE THREAD

**Issue by vans163** [elixirscript/elixirscript#386]
```
Symbol('wtf') == Symbol('wtf')
false

Symbol('wtf') === Symbol('wtf')
false

Symbol('wtf').toString() == Symbol('wtf').toString()
true
```
This seems to break a lot of assumptions..

Calling .toString() in tight loops seems not very performant either.

Maybe https://github.com/elixirscript/elixirscript/issues/373 needs to be revisited, perhaps instead of relying on javascript types which differ a lot from how erlang types work, we need to make our own types /+ leverage the term format.

**Comment by bryanjos** [comment]
What you are seeing is exactly how symbols work. ElixirScript uses Symbol.for to define symbols. This is to create a symbol with that name.
