### ISSUE TITLE
Equality of keys pull has reversed args

### ISSUE THREAD

**Issue by vans163** [elixirscript/elixirscript#414]
http://erlang.org/doc/man/maps.html#get-2
https://github.com/elixirscript/elixirscript/pull/410/files

This pull puts the map as the first arg, but it should be second

```
#It should be
:maps.get({"tuple_key"}, %{})

#instead this pull wants you to call it like
:maps.get(%{}, {"tuple_key"})
```

The result is Map.get with a tuple key always returns null.

**Comment by conradwt** [comment]
The first argument to `Map.get` and `Map.put` should be a `Map` and not a tuple per the Elixir documentation. Next, the key, `{"tuple_key"}`, doesn't exist in the map `%{}` so `nil` is the correct return value.  Please see the documentation here:

https://hexdocs.pm/elixir/Map.html

**Comment by bryanjos** [comment]
Looking at the connected PR, it looks like there was a bug with missing arguments to `is_key` calls in the erlang JavaScript module, but not with what is described in the issue's description.

**Comment by vans163** [comment]
This should be fixed and correct it was another issue once I looked into it.  I wonder thought by Map.get is broken still, I would assume it relies on :maps.get.
