### ISSUE TITLE
How to build elixirscript?

### ISSUE THREAD

**Issue by ilovezfs** [elixirscript/elixirscript#422]
I'm trying to get the Homebrew formula working for v0.31.0. Currently we do this
```
  def install
    ENV["MIX_ENV"] = "prod"

    system "mix", "local.hex", "--force"
    system "mix", "local.rebar", "--force"
    system "mix", "deps.get"
    system "npm", "install", *Language::Node.local_npm_install_args
    system "npm", "run", "build"
    system "mix", "clean"
    system "mix", "compile"
    system "mix", "dist"
    system "mix", "test"
    system "npm", "test"

    ENV.delete("MIX_ENV")
    system "mix", "docs"

    bin.install "elixirscript"
    prefix.install Dir["priv/*"]
    doc.install Dir["doc/*"]
  end
```

Looking at your Travis file, I tried adding the `yarn` dependency and making it
```
  def install
    ENV.deparallelize
    ENV["MIX_ENV"] = "prod"
    system "mix", "local.rebar", "--force"
    system "mix", "local.hex", "--force"
    system "make"
    system "make", "test"
    bin.install "elixirscript"
  end
```

A few issues so far:
1) without the deparallelize it seemed to fail
2) make test fails
3) there seems to no longer be an elixirscript binary output
4) I'm not sure what the docs commands should be now

**Comment by bryanjos** [comment]
@ilovezfs sorry, since 0.30.0 there isn't an elixirscript binary anymore as it uses some features that would make it very difficult to do. There may be a way to do so in the future, but I'm not sure yet. 

I guess to prevent any further confusion, is there a way to retire a homebrew package?

**Comment by ilovezfs** [comment]
@bryanjos would it not be useful to distribute elixirscript as a library in Homebrew?

**Comment by bryanjos** [comment]
@ilovezfs in its current state, no. Since the newer versions read from beam files in mix projects. The latest version can read from a file path, but still depends on being in a mix project (but not by much). It's possible to bundle that part into a binary, but it also would miss out on features like being able to use Elixir libraries. It's possible, but not a priority

**Comment by ilovezfs** [comment]
@bryanjos OK https://github.com/Homebrew/homebrew-core/pull/18977.
