### ISSUE TITLE
Is it possible to compile quoted or string?

### ISSUE THREAD

**Issue by grych** [elixirscript/elixirscript#444]
`ElixirScript.Compiler.compile` takes a module or a path for a "*.ex" file. Is it possible to compile AST or even a string?

Something like:
```elixir
iex(2)> m = quote do
...(2)> defmodule A do
...(2)> def a(), do: "a"
...(2)> end
...(2)> end
{:defmodule, [context: Elixir, import: Kernel],
 [
   {:__aliases__, [alias: false], [:A]},
   [
     do: {:def, [context: Elixir, import: Kernel],
      [{:a, [context: Elixir], []}, [do: "a"]]}
   ]
 ]}
iex(3)> ElixirScript.Compiler.compile m
```

Or:

```elixir
iex(3)> s = "IO.puts(1)"
"IO.puts(1)"
iex(4)> ElixirScript.Compiler.compile s
```

**Comment by bryanjos** [comment]
@grych Not currently. I think it could be possible in the future as long as the string or ast can be compiled and a beam file created.

**Comment by grych** [comment]
Thanks for info! I am looking forward to see this feature, as I want to integrate it with my project, https://github.com/grych/drab

**Comment by OvermindDL1** [comment]
It is pretty trivial to create a beam file in-memory actually, like very very trivial (it's the return value of the compile functions, exists only in memory).  If it were possible to pass that in-memory beam binary to elixirscript then you'd be able to handle any inline parsing of any code of any beam language.  :-)
