### ISSUE TITLE
in-browser Elixir parser / interpreter 

### ISSUE THREAD

**Issue by tclain** [elixirscript/elixirscript#447]
HI guys,
first of all, thanks for your hard work,  that rocks !

I was wondering if an initiative did exist to execute (or at least parse) elixir code completely in browser (for instance to build lightweight online tutorials). I'm sorry in advance if my question is a miscomprehension of elixirscript.

Thanks for your answer.

**Comment by bryanjos** [comment]
Hi @tclain, elixirscript's compiler depends on some features of erlang/otp itself. So it wouldn't be possible to do so at this time

**Comment by tclain** [comment]
I'll take this as a base : https://github.com/tryelixir/tryelixir
Thank you
