### ISSUE TITLE
Elixir + Wasm

### ISSUE THREAD

**Issue by jamen** [elixirscript/elixirscript#454]
Hey @bryanjos! I've been interested in your work here. What are your thoughts on WebAssembly? I began [elixir-wasm](https://github.com/jamen/elixir-wasm) to start this, and I've thought about using ElixirScript for creating JavaScript host bindings. I have some thoughts to share:

- WebAssembly compilers typically create JavaScript "host bindings", because the user would have to write their own to execute the WebAssembly program meaningfully. For example, see Emscripten's [preamble.js](https://github.com/emscripten-core/emscripten/blob/incoming/src/preamble.js) and Rust's [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen). This means the JS code generation is still useful for WebAssembly. Its also useful for an [asm.js](http://asmjs.org/) fallback.

- Standalone WebAssembly (without host bindings) is still important for environments that aren't JavaScript. People asked me about Elixir WASM with distributed platforms _more than_ regular web apps (for example [ewasm](https://github.com/ewasm)).

- I think an option for HTML output would be good to have 0 extra steps for running the code (whether its WebAssembly or JavaScript)

**Comment by bryanjos** [comment]
Hey @jamen, I can agree with mostly all of what you have said. I've peeked at your project a couple of times this year. I think one of the bigger issues is the lack of garbage collection in wasm currently. Any plans around that?

I'm down to help in any way I can towards the goal.

**Comment by jamen** [comment]
That is an important concern.  WebAssembly has a [garbage collection proposal](https://github.com/WebAssembly/gc), but in the meantime it would need its own garbage collection. I dont know exactly how I'll structure the odds and ends of the WebAssembly output yet, but for now I was seeing it its okay to start doing that here. Ultimately the goal is taking advantage of whatever APIs necessary to mimick BEAM processes and scheduling sufficiently, and compromising where it makes sense.

I'll return with more technical discussion and pull requests. This might take a while for me to wrap my head around (I'm no expert in WebAssembly, and especially not BEAM). But I'm determined to get _something_ and learn lots.

**Comment by fazibear** [comment]
Maybe this is the way you can go? https://github.com/bettio/AtomVM

**Comment by bryanjos** [comment]
Definitely something to do some research on

**Comment by jamen** [comment]
@lahwran I haven't been able to put much time into this. I played with ElixirScript's code a bit, but nothing worth showing yet. My focus has shifted away from WebAssembly lately, but I'm still interested in this, and any help is appreciated. 😄

**Comment by lahwran** [comment]
Oh man! I misunderstood from the readme at https://github.com/jamen/elixir-wasm that this whole github project was under initial development with this issue tracking it. I didn't realize that this would be a v2!

**Comment by foucist** [comment]
Leaving this link here for others to see:  https://github.com/lumen/lumen

**Comment by bryanjos** [comment]
Since Lumen exists now, I think this can be closed
