### ISSUE TITLE
Pragmatic question: working with JS Object

### ISSUE THREAD

**Issue by nrser** [elixirscript/elixirscript#490]
I'm in the process of evaluating ElixirScript for use along with the Elixir/Phoenix back-ends and JavaScript/TypeScript fronts we're developing. It is unlikely for "ElixirScript-only" front-ends to be viable for us (as I would guess is the case with many organizations) but I think we could realize great advantage writing specific components and libraries.

The major hang-up I'm hitting is JS `Object`/`Map` conversion - it looks like ElixirScript used to represent Elixir Map and Struct with standard JS Objects and Classes, but moved to Maps a few years back. Maps obviously correspond much better to Elixir, but, as I'm sure you're aware, they're essentially non-existent in the JS ecosystem, both in terms of use and support. React, Redux, Lodash... I can't recall seeing JS Maps used or supported anywhere.

Besides the annoyance and potential for error of coveting every time we cross the compilation line with an associative structure, it looks like `map_to_object` and `object_to_map` create *new* instances on every call, which loses us identity comparison (together with "immutable by practice") as a way of telling if something has changed in React and Redux, which is important from a performance standpoint.

If ElixirScript is preferring Elixir compatibility to JS ecosystem interop that's a totally reasonable choice - I'm sure there were tons of drawback to using Object and Class with their String/Symbol-only keys - but it does seem to lead in more of an "all or nothing" direction, which is not really somewhere we're willing to go with any JS tech.

Are there ways to work with Object in ElixirScript instead of Map to avoid the conversion and resulting identity change? Any other features or approaches for heavy interop and the Object/Map issue besides converting all the time?

Thanks, Neil.

**Comment by bryanjos** [comment]
Hi @nrser, the decision to use JS Maps over Objects was to make sure that there were no unexpected pitfalls to using maps as they are defined in Elixir and Erlang. They aren't exactly one to one.

**Comment by nrser** [comment]
As I said, I totally see the rationale - it matches Elixir's semantics much better, and then Elixir's structs _are_ maps, so there's that.

I honestly wish that that native JS Map was used and supported in the JS ecosystem due to the exact funkiness that I'm sure steered you guys away from using Object, but it's not used, it's not supported, and I doubt it will ever be.

My idea for potentially using ElixirScript would be to fork and replace the Map representation with Immutable.js Map/Record. That way we get immutability (which would seem to match Elixir even better), don't have to write our own deep update functions, and get better ecosystem support (crazy, right? But native JS Map has basically nothing... I brought it up to the Lodash people one and they were like "No... Why would anyone ever use a Map?").

Was that option considered as a backing representation? Any idea how much of a project it would be to swap in?

**Comment by nrser** [comment]
And since I closed the issue, for anyone that comes across this with the same question, I'm drawing the answer to be:

No, no direct Object support. You convert back and forth every time and all the time.
