### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by clmay** [elixirscript/elixirscript#495]
This project seems like it should have great promise, but there doesn't seem to be much activity. Is it still alive? Seeking maintainers? I would love to be able to write both back- and front-end in Elixir.

**Comment by bryanjos** [comment]
I haven't worked on this in a while. I think there are some changes that may need to occur to make it work with current elixir versions.

Since [Lumen](https://github.com/lumen/lumen) is a thing now, I've been focusing energy there

**Comment by clmay** [comment]
Lumen looks very cool, and a worthy project, for sure. Are the Gleam folks contributing, as well (I noticed it's in Rust)?

Thanks for the reply here. Maybe I'll have a look into what it would take to bring it current.
